# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41f967b022bb4033f7ac6e010dcbc3c5"
application_url = "https://espira-goldprice.onrender.com"
embedded = true
name = "Espira gold price update"
handle = "espira-gold-price-update"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://espira-goldprice.onrender.com/auth/callback",
  "https://espira-goldprice.onrender.com/auth/shopify/callback",
  "https://espira-goldprice.onrender.com/api/auth/callback"
]

[pos]
embedded = true

[build]
dev_store_url = "earnestminds.myshopify.com"
automatically_update_urls_on_dev = true
